import type { AppearanceSettings, NotificationSetting } from "./types";

export const defaultAppearanceSettings: AppearanceSettings = {
  theme: "light",
  color: "indigo",
  fontSize: 14,
  density: "comfortable",
  sidebar: "auto",
  locale: "vi",
  rowsPerPage: 20,
  dateFormat: "DD/MM/YYYY",
  animations: true,
  tooltip: true,
  performance: false,
  shortcuts: true,
};

export const mockNotificationData: NotificationSetting[] = [
  {
    channelId: "email",
    channelName: "Thông báo qua Email",
    items: [
      {
        id: "1",
        key: "low_stock_alert",
        label: "Cảnh báo tồn kho thấp",
        description: "Khi sản phẩm dưới mức tồn kho tối thiểu",
        isEnabled: true,
        isUrgent: true,
        channel: "email",
      },
      {
        id: "2",
        key: "new_inbound",
        label: "Thông báo nhập kho mới",
        description: "Khi có phiếu nhập hàng được tạo",
        isEnabled: true,
        isUrgent: false,
        channel: "email",
      },
      {
        id: "3",
        key: "outbound_notification",
        label: "Thông báo xuất kho",
        description: "Khi có đơn hàng xuất kho được xử lý",
        isEnabled: true,
        isUrgent: false,
        channel: "email",
      },
      {
        id: "4",
        key: "expiry_alert",
        label: "Cảnh báo hết hạn",
        description: "Khi sản phẩm sắp hết hạn sử dụng",
        isEnabled: true,
        isUrgent: true,
        channel: "email",
      },
      {
        id: "5",
        key: "weekly_report",
        label: "Báo cáo tồn kho hàng tuần",
        description: "Tóm tắt tồn kho và hoạt động hàng tuần",
        isEnabled: false,
        isUrgent: false,
        channel: "email",
      },
      {
        id: "6",
        key: "security_alert",
        label: "Cảnh báo bảo mật",
        description: "Đăng nhập bất thường, thay đổi quyền",
        isEnabled: true,
        isUrgent: true,
        channel: "email",
      },
    ],
  },
  {
    channelId: "push",
    channelName: "Thông báo đẩy trong ứng dụng",
    items: [
      {
        id: "7",
        key: "desktop_notification",
        label: "Thông báo desktop",
        description: "Hiển thị popup trên màn hình desktop",
        isEnabled: true,
        isUrgent: false,
        channel: "push",
      },
      {
        id: "8",
        key: "notification_sound",
        label: "Âm thanh thông báo",
        description: "Phát âm thanh khi có thông báo mới",
        isEnabled: false,
        isUrgent: false,
        channel: "push",
      },
      {
        id: "9",
        key: "device_vibration",
        label: "Rung thiết bị",
        description: "Rung thiết bị di động (nếu hỗ trợ)",
        isEnabled: true,
        isUrgent: false,
        channel: "push",
      },
      {
        id: "10",
        key: "urgent_notification",
        label: "Thông báo khẩn cấp",
        description: "Luôn hiển thị thông báo khẩn cấp",
        isEnabled: true,
        isUrgent: true,
        channel: "push",
      },
    ],
  },
  {
    channelId: "sms",
    channelName: "Thông báo khẩn cấp qua SMS",
    items: [
      {
        id: "11",
        key: "system_emergency",
        label: "Cảnh báo khẩn cấp hệ thống",
        description: "Hệ thống ngừng hoạt động, lỗi nghiêm trọng",
        isEnabled: true,
        isUrgent: true,
        channel: "sms",
      },
      {
        id: "12",
        key: "security_emergency",
        label: "Cảnh báo bảo mật",
        description: "Đăng nhập bất thường, thay đổi quyền quan trọng",
        isEnabled: true,
        isUrgent: true,
        channel: "sms",
      },
      {
        id: "13",
        key: "critical_stock",
        label: "Tồn kho khẩn cấp",
        description: "Sản phẩm quan trọng hết hàng hoàn toàn",
        isEnabled: true,
        isUrgent: true,
        channel: "sms",
      },
    ],
  },
];
